apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: myapp-pod
  name: myapp-pod
spec:
  containers:
  - image: nginx
    name: myapp-pod
    resources: {}
  tolerations:
  - key: "app"
    operator: "Equal"
    value: "blue"
    effect: "NoSchedule"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
